### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by kwlamb** [bgaifullin/jenkins-job-builder-active-choice#1]
I installed it via pip.
But, when I try to run JJB with your example job, I get this:
`jenkins_jobs.errors.JenkinsJobsException: Unknown entry point or macro 'active-choice' for component type: 'parameter'.`
Is there something I need to do after installing with pip?

**Comment by bgaifullin** [comment]
What version of JJB do you use ?

**Comment by kwlamb** [comment]
2.0.0.0b2

**Comment by bgaifullin** [comment]
Thanks, I will fix compatibility with JJB 2.x

**Comment by mrpity** [comment]
Sorry, but when you plan to fix this?

**Comment by bgaifullin** [comment]
I am very sorry for so late response.
I have pushed fix, please check.
