### ISSUE TITLE
Conflicts in JJB 3.9.0 with dynamic-reference

### ISSUE THREAD

**Issue by RuslanMarinin** [bgaifullin/jenkins-job-builder-active-choice#17]
jenkins_jobs.errors.JenkinsJobsException: Duplicate entry point found for component type: 'parameter', 'parameter',name: 'dynamic-reference'

How to avoid this behavior?

**Comment by martyn-beaumont** [comment]
Any update or workaround on this? 

Seems to be Python3, JJB 3.9.0 & this plugin issue.

jenkins_jobs.errors.JenkinsJobsException: Duplicate entry point found for component type: 'parameter', 'parameter',name: 'string'

**Comment by RuslanMarinin** [comment]
i use native support from master branch(no tag) of JJB
https://opendev.org/jjb/jenkins-job-builder/commit/f810d8bc308a8d5234e183012725bf3a47399e27
https://opendev.org/jjb/jenkins-job-builder/commit/15a0896791009815cfbec6e52bfd832e9cb39b7f

My dockerfile:
`FROM python:3

ENV BRANCH master
ENV VERSION 15a0896791009815cfbec6e52bfd832e9cb39b7f

WORKDIR /opt

RUN cd /opt \
	&& git clone -b ${BRANCH} https://opendev.org/jjb/jenkins-job-builder.git \
	&& cd jenkins-job-builder \
	&& git checkout ${VERSION} \
	&& cd /opt/jenkins-job-builder \
	&& pip install -r requirements.txt \
	&& python setup.py install \
	&& mkdir /.cache && chmod 777 /.cache \
	&& rm -R /opt/jenkins-job-builder

ENTRYPOINT ["/usr/local/bin/jenkins-jobs"]`
